apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-external-secret
spec:
  secretStoreRef:
    name: mysecretstore
    kind: SecretStore
  target:
    name: aws-secrets-extracted
  data:
    - secretKey: secret-key
      remoteRef:
        key: aws-secret
        property: key